export const styles = {
  page: {
    minHeight: "100vh",
    padding: "32px 20px",
    background:
      "linear-gradient(135deg, #eef7ff 0%, #f7fcf8 45%, #ffffff 100%)",
  },
  container: {
    maxWidth: "1180px",
    margin: "0 auto",
    display: "grid",
    gap: "24px",
  },
  heroPanel: {
    background: "#ffffff",
    borderRadius: "24px",
    padding: "24px",
    boxShadow: "0 18px 45px rgba(15, 23, 42, 0.08)",
    display: "grid",
    gap: "18px",
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
    alignItems: "center",
  },
  section: {
    background: "#ffffff",
    borderRadius: "22px",
    padding: "22px",
    boxShadow: "0 18px 45px rgba(15, 23, 42, 0.08)",
  },
  badge: {
    display: "inline-block",
    padding: "6px 12px",
    borderRadius: "999px",
    background: "#dff4ea",
    color: "#17633f",
    fontSize: "0.9rem",
    fontWeight: 600,
    cursor: "default",
    userSelect: "none",
    caretColor: "transparent",
  },
  title: {
    marginTop: "14px",
    marginBottom: "10px",
    color: "#0f172a",
    cursor: "default",
    userSelect: "none",
    caretColor: "transparent",
  },
  description: {
    margin: 0,
    color: "#475569",
    lineHeight: 1.7,
    cursor: "default",
    userSelect: "none",
    caretColor: "transparent",
  },
  heroMeta: {
    display: "grid",
    gap: "14px",
    gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
  },
  metaCard: {
    background: "#eef7ff",
    border: "1px solid #cfe2ff",
    borderRadius: "18px",
    padding: "18px",
    display: "grid",
    gap: "6px",
  },
  metaLabel: {
    color: "#2563eb",
    fontSize: "0.92rem",
    cursor: "default",
    userSelect: "none",
    caretColor: "transparent",
  },
  metaValue: {
    fontSize: "1.9rem",
    color: "#0f172a",
    cursor: "default",
    userSelect: "none",
    caretColor: "transparent",
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "18px",
  },
  card: {
    background: "#f8fbff",
    border: "1px solid #d8e7f5",
    borderRadius: "16px",
    padding: "16px",
  },
  cardText: {
    marginBottom: 0,
    color: "#475569",
    cursor: "default",
    userSelect: "none",
    caretColor: "transparent",
  },
  cardValue: {
    fontSize: "1.8rem",
    cursor: "default",
    userSelect: "none",
    caretColor: "transparent",
  },
  tabRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "12px",
  },
  tabButton: {
    border: "1px solid #bfdbfe",
    background: "#eff6ff",
    color: "#1d4ed8",
    padding: "12px 18px",
    borderRadius: "999px",
    fontWeight: 700,
    cursor: "pointer",
  },
  activeTabButton: {
    background: "#2563eb",
    color: "#ffffff",
    borderColor: "#2563eb",
  },
  contentGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: "18px",
  },
  fullWidthPanel: {
    gridColumn: "1 / -1",
  },
  subTitle: {
    marginTop: 0,
    color: "#0f172a",
    cursor: "default",
    userSelect: "none",
    caretColor: "transparent",
  },
  list: {
    margin: 0,
    paddingLeft: "18px",
    color: "#475569",
    lineHeight: 1.8,
    cursor: "default",
    userSelect: "none",
    caretColor: "transparent",
  },
  actionGroup: {
    display: "grid",
    gap: "12px",
  },
  actionButton: {
    border: "none",
    borderRadius: "14px",
    padding: "14px 16px",
    color: "#ffffff",
    fontWeight: 600,
    cursor: "pointer",
    textAlign: "left",
  },
  panelHeader: {
    display: "grid",
    gap: "8px",
    marginBottom: "18px",
  },
  helperText: {
    color: "#64748b",
    fontSize: "0.95rem",
    cursor: "default",
    userSelect: "none",
    caretColor: "transparent",
  },
  recordGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
    gap: "16px",
  },
  recordCard: {
    background: "#f8fbff",
    border: "1px solid #d8e7f5",
    borderRadius: "18px",
    padding: "18px",
    display: "grid",
    gap: "14px",
  },
  recordHeader: {
    display: "flex",
    gap: "10px",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  recordTitle: {
    margin: 0,
    color: "#0f172a",
    cursor: "default",
    userSelect: "none",
    caretColor: "transparent",
  },
  recordText: {
    margin: 0,
    color: "#475569",
    lineHeight: 1.6,
    cursor: "default",
    userSelect: "none",
    caretColor: "transparent",
  },
  recordMeta: {
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    color: "#2563eb",
    fontSize: "0.92rem",
    cursor: "default",
    userSelect: "none",
    caretColor: "transparent",
  },
  statusBadge: {
    borderRadius: "999px",
    padding: "6px 10px",
    fontSize: "0.84rem",
    fontWeight: 700,
    textTransform: "capitalize",
    cursor: "default",
    userSelect: "none",
    caretColor: "transparent",
  },
  rowActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
  },
  smallButton: {
    border: "none",
    borderRadius: "12px",
    padding: "10px 14px",
    color: "#ffffff",
    fontWeight: 600,
    cursor: "pointer",
  },
  alertList: {
    display: "grid",
    gap: "12px",
  },
  alertItem: {
    background: "#eef7ff",
    border: "1px solid #cfe2ff",
    borderRadius: "14px",
    padding: "14px 16px",
    color: "#1e3a8a",
    cursor: "default",
    userSelect: "none",
    caretColor: "transparent",
  },
  tableWrapper: {
    overflowX: "auto",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  tableHead: {
    textAlign: "left",
    padding: "14px",
    background: "#eff6ff",
    color: "#1d4ed8",
    borderBottom: "1px solid #bfdbfe",
    cursor: "default",
    userSelect: "none",
    caretColor: "transparent",
  },
  tableCell: {
    padding: "14px",
    borderBottom: "1px solid #e2e8f0",
    color: "#334155",
    cursor: "default",
    userSelect: "none",
    caretColor: "transparent",
  },
  patientStatus: {
    display: "inline-block",
    borderRadius: "999px",
    padding: "5px 10px",
    fontSize: "0.82rem",
    fontWeight: 700,
    textTransform: "capitalize",
    cursor: "default",
    userSelect: "none",
    caretColor: "transparent",
  },
  availableBadge: {
    borderRadius: "999px",
    padding: "6px 10px",
    fontSize: "0.84rem",
    fontWeight: 700,
    background: "#dcfce7",
    color: "#166534",
    cursor: "default",
    userSelect: "none",
    caretColor: "transparent",
  },
  unavailableBadge: {
    borderRadius: "999px",
    padding: "6px 10px",
    fontSize: "0.84rem",
    fontWeight: 700,
    background: "#fee2e2",
    color: "#991b1b",
    cursor: "default",
    userSelect: "none",
    caretColor: "transparent",
  },
};

export const valueColors = {
  appointments: { color: "#0f766e" },
  patients: { color: "#1d4ed8" },
  reports: { color: "#b45309" },
};

export const buttonColors = {
  appointments: { background: "#0f766e" },
  records: { background: "#2563eb" },
  availability: { background: "#0f172a" },
  block: { background: "#dc2626" },
};

export function getAppointmentStatusStyle(status) {
  const palette = {
    confirmed: { background: "#dcfce7", color: "#166534" },
    waiting: { background: "#fef3c7", color: "#92400e" },
    completed: { background: "#dbeafe", color: "#1d4ed8" },
  };

  return {
    ...styles.statusBadge,
    ...(palette[status] || palette.waiting),
  };
}

export function getPatientStatusStyle(status) {
  const palette = {
    stable: { background: "#dcfce7", color: "#166534" },
    attention: { background: "#fef3c7", color: "#92400e" },
    critical: { background: "#fee2e2", color: "#991b1b" },
  };

  return {
    ...styles.patientStatus,
    ...(palette[status] || palette.stable),
  };
}
